imports:
  - { resource: '../api_doc.yaml' }

nelmio_api_doc:
  documentation:
    info:
      title: DV Campus Notelist
      description: You notes can stored here
      version: 0.1.0
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Value: Bearer {token}'
        name: Authorization
        in: header
    security:
      - Bearer: []

  routes:
    path_patterns:
      - ^/api(?!/doc)
